AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "pkg/**/*"

Style/Documentation:
  Exclude:
    - "spec/**/*"
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Layout/LineLength:
  Max: 160
Naming/FileName:
  Exclude:
    - "lib/cekat-event-sdk.rb"
