<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <ProjectReference Include="..\..\src\Cekat.EventSdk.AspNetCore\Cekat.EventSdk.AspNetCore.csproj" />
  </ItemGroup>
</Project>
